# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2ruWp6-T-c-wkBB40FkCOv51pJecMl2
"""

import streamlit as st
import numpy as np
from PIL import Image

@st.cache_resource
def load_model():
    return tf.keras.models.load_model("model_apel_cnn.h5")

model = load_model()

st.set_page_config(
    page_title="Klasifikasi Apel",
    page_icon="🍎",
    layout="centered"
)

st.title("🍎 Klasifikasi Apel CNN")
st.write("Upload gambar untuk melakukan prediksi menggunakan model CNN.")

uploaded_file = st.file_uploader(
    "Pilih gambar",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    st.image(
        image,
        caption="Gambar yang diupload",
        use_container_width=True
    )

    img = image.resize((128, 128))
    img_array = np.array(img, dtype=np.float32) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    with st.spinner("Memproses gambar..."):
        pred = model.predict(img_array, verbose=0)[0][0]

    st.subheader("Hasil Prediksi")

    if pred >= 0.5:
        st.success("Kelas 1")
        st.write(f"Probabilitas: {pred*100:.2f}%")
    else:
        st.warning("Kelas 0")
        st.write(f"Probabilitas: {(1-pred)*100:.2f}%")

    st.write(f"Output sigmoid: {pred:.4f}")
